/* Calendar, room workflows and saved-data insights. No external chart dependency. */
let calendarMonth = null;
let calendarLayout = 'Month';
let insightPeriod = 'Month';
let taskStatus = 'All';
let taskEnergy = '';
let taskMinutes = '';
let activeRoom = '';
const roomIdeas = {
  Kitchen: ['Move dishes to the sink', 'Clear one counter', 'Wipe the counter'],
  'Living Room': ['Return three items to their homes', 'Fold the throw', 'Clear the coffee table'],
  Bedroom: ['Make the bed', 'Put away five pieces of clothing', 'Clear one bedside surface'],
  Bathroom: ['Put products back', 'Wipe the sink', 'Replace the hand towel'],
  Office: ['Collect five loose papers', 'Clear space on the desk', 'Put stationery away'],
  Entryway: ['Pair the shoes', 'Hang coats and bags', 'Clear a place for your keys']
};
function localDate(d) { return `${String(d.getFullYear()).padStart(4,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function dateObject(s) { const [y,m,d]=s.split('-').map(Number);const value=new Date(2000,0,1,12);value.setFullYear(y,m-1,d);return value; }
function shiftDate(s,n) { const d=dateObject(s);d.setDate(d.getDate()+n);return localDate(d); }
function monthShift(s,n) { const d=dateObject(s+'-01');d.setMonth(d.getMonth()+n);return localDate(d).slice(0,7); }
function dateLabel(s,short=false) { return dateObject(s).toLocaleDateString('en-US',short?{month:'short',day:'numeric'}:{weekday:'long',month:'long',day:'numeric',year:'numeric'}); }
function isDate(s){ if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;return localDate(dateObject(s))===s; }
function rangeFor(period=insightPeriod,anchor=selectedDate) {
  if(period==='Week'){ const d=dateObject(anchor),start=shiftDate(anchor,-((d.getDay()+6)%7));return {start,end:shiftDate(start,6),label:`${dateLabel(start,true)} – ${dateLabel(shiftDate(start,6),true)}`}; }
  const start=anchor.slice(0,7)+'-01';return {start,end:shiftDate(monthShift(start.slice(0,7),1)+'-01',-1),label:dateObject(start).toLocaleDateString('en-US',{month:'long',year:'numeric'})};
}
function inRange(date,range){return date>=range.start&&date<=range.end;}
function reportFor(range) {
  const planned=state.tasks.filter(t=>inRange(t.date,range));
  const completed=state.tasks.filter(t=>t.done&&inRange(t.completedDate||t.date,range));
  const sessions=state.logs.filter(l=>inRange(l.date,range)&&l.type==='sprint');
  return {planned,completed,sessions,donePlanned:planned.filter(t=>t.done).length,minutes:sessions.reduce((s,l)=>s+Number(l.minutes||0),0),activeDays:new Set(completed.map(t=>t.completedDate||t.date)).size,rooms:new Set(completed.map(t=>t.room)).size};
}
function periodControls(kind='insight'){
 return `<div class="period-controls"><div class="segmented" aria-label="Report period">${['Week','Month'].map(p=>`<button data-period="${p}" aria-pressed="${insightPeriod===p}" class="${insightPeriod===p?'selected':''}">${p}</button>`).join('')}</div><button class="secondary" data-period-shift="-1" aria-label="Previous period">←</button><input type="${insightPeriod==='Month'?'month':'date'}" id="insight-date" aria-label="Report date" value="${insightPeriod==='Month'?selectedDate.slice(0,7):selectedDate}"><button class="secondary" data-period-shift="1" aria-label="Next period">→</button><button class="secondary" data-action="insight-today">Today</button></div>`;
}
function metricCard(value,label,detail,ic){return `<article class="card metric"><span class="metric-icon">${icon(ic)}</span><strong>${value}</strong><span>${label}</span><small>${detail}</small></article>`;}
function activityChart(range,compact=false){
 const ds=[];for(let d=range.start;d<=range.end;d=shiftDate(d,1)){ds.push({date:d,total:state.tasks.filter(t=>t.done&&(t.completedDate||t.date)===d).length});}
 const max=Math.max(1,...ds.map(d=>d.total));
 return `<div class="chart-summary"><span>Completed tasks</span><small>${range.label}</small></div><div class="activity-chart ${compact?'compact':''}" role="group" aria-label="Completed tasks by day">${ds.map((d,i)=>`<button class="chart-column" data-chart-date="${d.date}" aria-label="${dateLabel(d.date)}: ${d.total} completed tasks"><span class="bar-tip">${d.total}</span><span class="chart-track"><i style="height:${d.total/max*100}%" class="${d.total?'has-value':''}"></i></span><span class="chart-day">${ds.length<=7?dateObject(d.date).toLocaleDateString('en-US',{weekday:'narrow'}):i%5===0||i===ds.length-1?dateObject(d.date).getDate():''}</span></button>`).join('')}</div>${!ds.some(x=>x.total)?'<p class="chart-empty">A quiet start. Your completed tasks will appear here.</p>':''}`;
}
function categoryChart(range){
 const report=reportFor(range),colors=['var(--main)','#82916c','#b18d59','#b9af9a'];let offset=0;const cats=['Cleaning','Decluttering','Rooms','Routines'];
 const counts=cats.map(cat=>report.completed.filter(t=>t.category===cat).length),total=counts.reduce((a,b)=>a+b,0);
 const stops=counts.map((n,i)=>{const start=offset;offset+=total?n/total*100:0;return `${colors[i]} ${start}% ${offset}%`}).join(',');
 return `<div class="category-body"><div class="category-ring" style="background:${total?'conic-gradient('+stops+')':'var(--line)'}"><div><strong>${total}</strong><small>tasks</small></div></div><div class="category-legend">${cats.map((cat,i)=>`<button data-category-detail="${cat}"><span class="dot" style="background:${colors[i]}"></span><span>${cat}</span><strong>${counts[i]}</strong></button>`).join('')}</div></div>`;
}
function progressPage(){
 const range=rangeFor(),report=reportFor(range);
 return heading('Small steps, made visible','A record of what you did. No streaks to protect, no missed-day penalties.',goButton('Print / PDF','Print Center','note'))+
 periodControls()+`<p class="range-label">${range.label}${state.demo?' · Includes your starting sample checklist':''}</p><div class="metrics-grid">${metricCard(report.completed.length,'Tasks completed','Saved completions in this period','check')}${metricCard(report.activeDays,'Days with a small win','Every return is a fresh start','calendar')}${metricCard(report.minutes,'Focus minutes','Completed timer sessions only','clock')}${metricCard(report.rooms,'Spaces cared for','Rooms with a completed task','home')}</div><div class="insights-grid"><section class="card"><div class="card-title"><h2>Your rhythm</h2><span class="muted">Tap a day to see its wins</span></div>${activityChart(range)}</section><section class="card"><div class="card-title"><h2>Where your effort went</h2></div>${categoryChart(range)}</section></div><div class="insights-grid"><section class="card"><div class="card-title"><h2>Room by room</h2><span class="muted">Completed in this period</span></div><div class="room-chart">${state.rooms.map(r=>{const n=report.completed.filter(t=>t.room===r.name).length;return `<button data-room="${esc(r.name)}"><span>${esc(r.name)}</span><span class="bar"><i style="width:${report.completed.length?n/report.completed.length*100:0}%"></i></span><strong>${n}</strong></button>`}).join('')}</div></section><section class="card"><div class="card-title"><h2>A flexible plan</h2></div><p class="plan-ratio"><strong>${report.donePlanned}</strong> of ${report.planned.length} scheduled tasks completed</p><div class="bar large"><i style="width:${report.planned.length?report.donePlanned/report.planned.length*100:0}%"></i></div><p class="muted">Based on tasks scheduled in this period. Completing a task on a different day records the win on the day you actually finished.</p>${goButton('Open calendar','Calendar','calendar')}</section></div><section class="card activity-log"><div class="card-title"><h2>Your wins</h2><span class="muted">${range.label}</span></div>${report.completed.length||report.sessions.length?`<div class="history">${report.completed.sort((a,b)=>(b.completedDate||b.date).localeCompare(a.completedDate||a.date)).map(t=>`<div><span>${icon('check')} ${esc(t.title)}</span><button class="link" data-open-date="${t.date}">${dateLabel(t.completedDate||t.date,true)}</button></div>`).join('')}${report.sessions.map(l=>`<div><span>${icon('clock')} ${esc(l.title)}</span><span>${l.minutes} min · ${dateLabel(l.date,true)}</span></div>`).join('')}</div>`:'<p class="muted">Nothing logged here yet. Start with one small task when you’re ready.</p>'}</section>`;
}
function calendarView(){
 calendarMonth=calendarMonth||selectedDate.slice(0,7);
 const first=calendarMonth+'-01',start=shiftDate(first,-((dateObject(first).getDay()+6)%7));const monthName=dateObject(first).toLocaleDateString('en-US',{month:'long',year:'numeric'});
 const selected=state.tasks.filter(t=>t.date===selectedDate);
 const days=Array.from({length:42},(_,i)=>shiftDate(start,i));
 return heading('A little space for your plans','Plan gently. Move things when life changes.',`<button class="primary" data-add-day="${selectedDate}">${icon('plus')} Add to ${dateLabel(selectedDate,true)}</button>`)+`<div class="calendar-toolbar"><div class="calendar-month"><button class="secondary" data-month-shift="-1" aria-label="Previous month">←</button><h3>${monthName}</h3><button class="secondary" data-month-shift="1" aria-label="Next month">→</button></div><div class="toolbar"><input type="month" id="calendar-month" aria-label="Go to month and year" value="${calendarMonth}"><button class="secondary" data-action="calendar-today">Today</button><div class="segmented">${['Month','Agenda'].map(x=>`<button data-calendar-layout="${x}" class="${calendarLayout===x?'selected':''}" aria-pressed="${calendarLayout===x}">${x}</button>`).join('')}</div></div></div><div class="calendar-layout"><section class="card calendar-card">${calendarLayout==='Month'?`<div class="calendar-weekdays">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid" role="group" aria-label="${monthName}">${days.map(date=>{const tasks=state.tasks.filter(t=>t.date===date),done=tasks.filter(t=>t.done).length;return `<button class="calendar-day ${date.slice(0,7)!==calendarMonth?'outside':''} ${date===today()?'today':''} ${date===selectedDate?'selected':''}" data-calendar-date="${date}" aria-pressed="${date===selectedDate}" aria-label="${dateLabel(date)}, ${tasks.length} tasks, ${done} completed"><span class="date-number">${dateObject(date).getDate()}</span>${tasks.length?`<span class="day-dots">${tasks.slice(0,4).map(t=>`<i class="${t.done?'complete':''}"></i>`).join('')}</span><small>${done}/${tasks.length}<span class="desktop-only"> complete</span></small>`:''}</button>`}).join('')}</div><div class="calendar-key"><span><i></i> Planned</span><span><i class="complete"></i> Complete</span><span>Plans can always move.</span></div>`:`<div class="agenda">${state.tasks.filter(t=>t.date.startsWith(calendarMonth)).sort((a,b)=>a.date.localeCompare(b.date)).map(t=>`<button data-calendar-date="${t.date}"><span>${dateLabel(t.date,true)}</span><strong>${esc(t.title)}</strong><small>${t.done?'Complete':esc(t.room)+' · '+t.minutes+' min'}</small></button>`).join('')||'<p class="muted">A clear month. Pick a day and add one small plan.</p>'}</div>`}</section><aside class="card day-plan"><span class="eyebrow">YOUR DAY</span><h3>${dateLabel(selectedDate,true)}</h3><p class="muted">${selected.length} tasks · ${selected.filter(t=>!t.done).reduce((s,t)=>s+t.minutes,0)} min planned</p>${taskRows(selected,true)}<button class="secondary full-width" data-add-day="${selectedDate}">${icon('plus')} Add a small task</button><p class="gentle-note">Leave some space for the unexpected.</p></aside></div>`;
}
function miniCalendar(){const ds=Array.from({length:7},(_,i)=>shiftDate(today(),i));return `<section class="card mini-calendar"><div class="card-title"><h2>A little look ahead</h2>${goButton('Calendar','Calendar','','link')}</div><div class="week-strip">${ds.map(date=>{const n=state.tasks.filter(t=>t.date===date).length;return `<button data-open-date="${date}" class="${date===today()?'today':''}" aria-label="${dateLabel(date)}, ${n} tasks"><span>${dateObject(date).toLocaleDateString('en-US',{weekday:'short'})}</span><strong>${dateObject(date).getDate()}</strong><i class="${n?'has-tasks':''}"></i></button>`}).join('')}</div></section>`;}
function homeInsights(){const range=rangeFor('Week',today());return `<section class="card home-rhythm"><div class="card-title"><h2>Small wins this week</h2>${goButton('View progress','Progress','','link')}</div>${activityChart(range,true)}</section>`;}
function roomDetail(){
 const name=activeRoom||state.rooms[0]?.name||'Your room',tasks=state.tasks.filter(t=>t.room===name),active=tasks.filter(t=>!t.done).sort((a,b)=>a.date.localeCompare(b.date)),done=tasks.filter(t=>t.done),ideas=roomIdeas[name]||['Return three items to their homes','Clear one small surface','Put away what you used'];
 return `<div class="toolbar">${goButton('← All rooms','Rooms','','link')}</div><div class="room-detail-hero">${photo(name)}<div><span class="eyebrow">ONE SPACE AT A TIME</span><h2>${esc(name)}</h2><p>Clear a little space. Keep a little breathing room.</p><button class="primary" data-add-room-task="${esc(name)}">${icon('plus')} Add a task</button></div></div><div class="room-workspace"><section class="card"><div class="card-title"><h2>Your next small steps</h2><span class="muted">${active.length} planned</span></div>${taskRows(active,true)}<details class="completed-details"><summary>Completed tasks · ${done.length}</summary>${taskRows(done,true)}</details></section><section class="card"><span class="eyebrow">A ${name==='Kitchen'?'KITCHEN':'ROOM'} RESET</span><h3>A simple place to start</h3><div class="reset-steps">${ideas.map((s,i)=>`<div><span>${i+1}</span><p>${esc(s)}</p></div>`).join('')}</div><button class="primary" data-room-plan="${esc(name)}">Use this small plan ${icon('arrow')}</button><p class="gentle-note">One step is enough. The rest can wait.</p></section></div>`;
}
function resetFlow(){return `<section class="card flow-card"><div class="card-title"><h2>A simple path through clutter</h2><span class="muted">One item at a time</span></div><div class="flow-diagram">${[['1','Choose one item','Start with what is closest.'],['2','Give it a place','Keep · Move · Donate · Trash'],['3','Finish this small step','Put it away, then pause.']].map(([n,t,d])=>`<div><span>${n}</span><strong>${t}</strong><p>${d}</p></div>`).join('')}</div></section>`;}
function insightDetail(kind,value){const range=rangeFor();let tasks=reportFor(range).completed;if(kind==='date')tasks=state.tasks.filter(t=>t.done&&(t.completedDate||t.date)===value);else tasks=tasks.filter(t=>t.category===value);openDialog(`<span class="eyebrow">SAVED COMPLETIONS</span><h2>${kind==='date'?dateLabel(value,true):esc(value)}</h2>${tasks.length?taskRows(tasks,true):'<p class="muted">No completed tasks here yet. Quiet days are allowed.</p>'}`);}
function insightClick(b){const d=b.dataset;if(d.action==='this-week-progress'){selectedDate=today();insightPeriod='Week';go('Progress');return true}if(d.openDate){selectedDate=d.openDate;calendarMonth=d.openDate.slice(0,7);go('Calendar');return true}if(d.calendarDate){selectedDate=d.calendarDate;if(d.calendarDate.slice(0,7)!==calendarMonth)calendarMonth=d.calendarDate.slice(0,7);render();return true}if(d.monthShift){calendarMonth=monthShift(calendarMonth||selectedDate.slice(0,7),Number(d.monthShift));selectedDate=calendarMonth+'-01';render();return true}if(d.calendarLayout){calendarLayout=d.calendarLayout;render();return true}if(d.addDay){selectedDate=d.addDay;add('Task','',{date:d.addDay,room:roomFilter});return true}if(d.period){insightPeriod=d.period;render();return true}if(d.periodShift){selectedDate=insightPeriod==='Week'?shiftDate(selectedDate,Number(d.periodShift)*7):monthShift(selectedDate.slice(0,7),Number(d.periodShift))+'-01';render();return true}if(d.chartDate){insightDetail('date',d.chartDate);return true}if(d.categoryDetail){insightDetail('category',d.categoryDetail);return true}if(d.addRoomTask){add('Task','',{room:d.addRoomTask,date:today(),category:'Rooms'});return true}if(d.roomPlan){const ideas=roomIdeas[d.roomPlan]||['Return three items to their homes','Clear one surface','Put away what you used'];let count=0;for(const title of ideas){if(state.tasks.some(t=>!t.done&&t.date===today()&&t.room===d.roomPlan&&t.title===title))continue;state.tasks.push({id:uid(),title,room:d.roomPlan,minutes:3,effort:'A little',category:'Rooms',date:today(),repeat:'None',done:false});count++}save();render();toast(count?`${count} small steps added to today`:'This plan is already waiting for you');return true}if(d.action==='calendar-today'){selectedDate=today();calendarMonth=today().slice(0,7);render();return true}if(d.action==='insight-today'){selectedDate=today();render();return true}return false;}
function insightChange(t){if(t.id==='calendar-month'&&t.value){calendarMonth=t.value;selectedDate=t.value+'-01';render();return true}if(t.id==='insight-date'&&t.value){selectedDate=t.value.length===7?t.value+'-01':t.value;render();return true}if(t.id==='task-status'){taskStatus=t.value;render();return true}if(t.id==='task-energy'){taskEnergy=t.value;render();return true}if(t.id==='task-minutes'){taskMinutes=t.value;render();return true}return false;}
function valid(s){
 if(!s||s.product!=='aurely-home-reset'||![1,2].includes(s.version)||!['tasks','rooms','notes','supplies','members','laundry','routines','logs','challenge','plans'].every(k=>Array.isArray(s[k])))return false;
 const str=(v,max=5000)=>typeof v==='string'&&v.length<=max;
 if(!s.tasks.every(t=>t&&str(t.id,100)&&/^[a-zA-Z0-9_-]+$/.test(t.id)&&str(t.title,160)&&str(t.room,120)&&isDate(t.date)&&Number.isInteger(t.minutes)&&t.minutes>=1&&t.minutes<=480&&(!t.completedDate||isDate(t.completedDate))))return false;
 if(!s.rooms.every(r=>r&&str(r.id,100)&&/^[a-zA-Z0-9_-]+$/.test(r.id)&&str(r.name,120)))return false;
 if(!['notes','supplies','members','laundry'].every(k=>s[k].every(x=>x&&str(x.id,100)&&/^[a-zA-Z0-9_-]+$/.test(x.id)&&str(x.title))))return false;
 if(!s.routines.every(r=>r&&str(r.id,100)&&/^[a-zA-Z0-9_-]+$/.test(r.id)&&str(r.title,160)&&Array.isArray(r.steps)&&r.steps.every(x=>str(x,500))&&Number.isFinite(r.minutes)))return false;
 if(!s.logs.every(l=>l&&str(l.id,100)&&str(l.title)&&isDate(l.date)&&Number.isFinite(l.minutes)&&l.minutes>=0))return false;
 if(!s.challenge.every(n=>Number.isInteger(n)&&n>=1&&n<=7))return false;
 return true;
}
function migrateState(s){
 const t={...baseTheme,...s.theme};for(const k of ['main','accent','bg'])if(!/^#[0-9a-f]{6}$/i.test(t[k]))t[k]=baseTheme[k];
 for(const [key,allowed] of Object.entries({ui:['Inter','Arial','Verdana','Trebuchet MS'],heading:['Georgia','Palatino','Times New Roman'],hand:['Kalam','Caveat','Patrick Hand','Dancing Script','Sacramento'],coverage:['Accents','Headings','Full Look']}))if(!allowed.includes(t[key]))t[key]=baseTheme[key];
 t.size=[15,16,17,18].includes(Number(t.size))?Number(t.size):15;t.calm=Boolean(t.calm);t.night=Boolean(t.night);
 return {...s,version:2,name:typeof s.name==='string'?s.name.slice(0,30):'',theme:t,tasks:s.tasks.map(task=>({...task,done:!!task.done,effort:task.effort||'A little',category:task.category||'Cleaning',repeat:task.repeat||'None'})),logs:s.logs.map(l=>({...l,type:l.type||(l.title.includes('focus sprint completed')||l.title==='Focus sprint completed'?'sprint':'activity')}))};
}
function saveSprint(){try{localStorage.setItem(KEY+'-sprint',JSON.stringify(timer))}catch{}}
function restoreSprint(){try{const t=JSON.parse(localStorage.getItem(KEY+'-sprint')||'null');if(t&&Number.isFinite(t.total)&&t.total>=60&&t.total<=10800&&Number.isFinite(t.remaining)&&t.remaining>=0&&t.remaining<=t.total&&Number.isFinite(t.end)){timer={...t,running:!!t.running};if(timer.running)timer.remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));}}catch{}}
